### ISSUE TITLE
BUG: Crash When Non-Armor is Placed into Armor Slot

### ISSUE THREAD

**Issue by rpeters54** [Spicy-Boy/Super-Better-Than-Wolves-2.0#13]
While in my inventory, I selected a stack of 8 leather and left or right-clicked (I don't remember which) 
on the Chestplate Armor Slot. After doing that, the game crashed.

Here's the crash report that was generated:
[crash-2024-06-18_15.03.09-client.txt](https://github.com/user-attachments/files/15893201/crash-2024-06-18_15.03.09-client.txt)

From what I can tell, the function determining whether or not the item 
placed in the armor slot can be worn is throwing a NullPtrException.

**Comment by Spicy-Boy** [comment]
Well dang, I thought I fixed that already. Will add to hotfix.

**Comment by Spicy-Boy** [comment]
FIXED!
https://github.com/Spicy-Boy/Super-Better-Than-Wolves-2.0/releases/tag/beta2.5_june
